name: Testing Apps

on: [push]

jobs:
  make-testing:
    name: Checking application
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: "Installing dependencies"
        run: python3 -m pip install -r requirements.txt
        shell: bash

      - name: Checking the application with stdin and stdout
        run: |
          if ! cmp <(python3 src/main.py < data/seqs.in) data/seqs.out; then
            echo "Incorrect output for python3 src/main.py < data/seqs.in"
            diff <(python3 src/main.py < data/seqs.in) data/seqs.out
          fi
        shell: bash

      - name: Checking the application with file and stdout
        run: |
          out=$(mktemp /tmp/ctib.XXXXXX)
          python3 src/main.py data/seqs.in $out
          if ! cmp $out data/seqs.out; then
            echo "Incorrect output for python3 src/main.py data/seqs.in $out"
            diff $out data/seqs.out
          fi
          rm $out
        shell: bash
